version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  email-worker:
    build: .
    command: node src/workers/emailWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  tracking-worker:
    build: .
    command: node src/workers/trackingWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  risk-worker:
    build: .
    command: node src/workers/riskWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  report-worker:
    build: .
    command: node src/workers/reportWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./uploads:/app/uploads

  playbook-worker:
    build: .
    command: node src/workers/playbookWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  enrichment-worker:
    build: .
    command: node src/workers/enrichmentWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  alert-worker:
    build: .
    command: node src/workers/alertWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  soar-notification-worker:
    build: .
    command: node src/workers/notificationWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

  analytics-worker:
    build: .
    command: node src/workers/analyticsWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./uploads:/app/uploads

  soar-integration-worker:
    build: .
    command: node src/workers/integrationWorker.js
    env_file:
      - config/.env
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
